### ISSUE TITLE
Add project submission

### ISSUE THREAD

**Issue by SaliBhdr** [matnbaz/matnbaz#10]
My name as a github user is in the website but the problem is 3 of my projects are there and one of my projects that has the most stars and download is not on the list. So its better to add a place for submitting project along with users.

**Comment by alitnk** [comment]
assuming the repository you mentioned is `SaliBhdr/typhoon-iran-cities`, yes there's a problem. I will take care of it as soon as i can as it should have been automatically added, I **think** i know where the issue is coming from.

Thanks for opening the issue.

**Comment by SaliBhdr** [comment]
@alitnk 
No problem. Love your project and I hope it will grow soon.

**Comment by alitnk** [comment]
This will fix it https://github.com/matnbaz/matnbaz/commit/0bae300651e439093176986cffb8df4b83d1d26d. Your repository will soon get added to the site automatically.
Again, thanks for reporting the issue.
