### ISSUE TITLE
USER-PROFILE-SEO optimzation for user profile - need to add person schema 

### ISSUE THREAD

**Issue by pooooriya** [matnbaz/matnbaz#109]
we need to add person schema to show a better search results
check out this section and json-ld
https://schema.org/Person

```
<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "Person",
  "address": {
    "@type": "PostalAddress",
    "addressLocality": "Seattle",
    "addressRegion": "WA",
    "postalCode": "98052",
    "streetAddress": "20341 Whitworth Institute 405 N. Whitworth"
  },
  "colleague": [
    "http://www.xyz.edu/students/alicejones.html",
    "http://www.xyz.edu/students/bobsmith.html"
  ],
  "email": "mailto:jane-doe@xyz.edu",
  "image": "janedoe.jpg",
  "jobTitle": "Professor",
  "name": "Jane Doe",
  "telephone": "(425) 123-4567",
  "url": "http://www.janedoe.com"
}
</script>

```

**Comment by alitnk** [comment]
This will be implemented using the [next-seo](https://github.com/garmeeh/next-seo) package.

**Comment by alitnk** [comment]
The only data we can provide for this schema is name, website URL (if available) and potentially image - which I wouldn't consider sufficient/applicable as they are expected to be actual photos of the person and that isn't always the case with GitHub images.
Also GitHub doesn't do schemas for users either. I suppose his would make more sense if we had more data on the users.
