### ISSUE TITLE
href link problem

### ISSUE THREAD

**Issue by amirhallaji** [matnbaz/matnbaz#128]
**Describe the bug**
Hi,
I want to announce that the href link in someone's profile is not correct.
It should be addressed absolute instead of relative. For instance, see [this](https://matnbaz.net/en/github/amirhallaji) page and click on my website. You'll notice what I mean.

**Comment by alitnk** [comment]
Hi, thanks for reporting the bug.
apparently this only happens when the URL does not contain an scheme. (http:// or https://)

Will fix this very soon.
