### ISSUE TITLE
Invalid Discord Community Link

### ISSUE THREAD

**Issue by faridvatani** [matnbaz/matnbaz#13]
Hi
I guess your invite [link](https://discord.com/invite/SNHSYWsKYQ) may have expired.

**Comment by alitnk** [comment]
Hi, that's weird cause it's working for me. can you try the URL again? 
If you still couldn't get in the server try this link I just created: https://discord.gg/D7McXzvf

**Comment by faridvatani** [comment]
It works, Thank you
