### ISSUE TITLE
internal server error on new user submission

### ISSUE THREAD

**Issue by hossein13m** [matnbaz/matnbaz#265]
When trying to add a new user, I happen to see two problems. 

- Although the request fails, the server sends a response with a status code of 200, which is not ideal!
- The more important issue is that the request fails on adding a new user. I have attached a file that contains the request's cURL so you can check it out.

[cURL.txt](https://github.com/matnbaz/matnbaz/files/8519553/cURL.txt)

**Comment by alitnk** [comment]
Thanks for the report - the GitHub key was expired and all the requests that used the GitHub API were failing.

Should be working properly now.
