### ISSUE TITLE
Why can't add new user?

### ISSUE THREAD

**Issue by TREER00T** [matnbaz/matnbaz#275]
من این خطا رو موقعه ثبت کاربر دریافت کردم 

خطایی پیش آمد، لطفا بعدا دوباره تلاش کنید.

الان حدودا یک ماهی هست که همین خطا رو میده  ، آیا این سرویس در حال حاظر قطع هست؟

**Comment by pooooriya** [comment]
@alitnk

**Comment by alitnk** [comment]
سلام دوستان
یه مشکلی داره بک‌اند مون که فعلا با ری‌استارت دستی حل میشه ولی باید وقت بذارم و شناسایی کنم مشکل رو...

**Comment by TREER00T** [comment]
> سلام دوستان یه مشکلی داره بک‌اند مون که فعلا با ری‌استارت دستی حل میشه ولی باید وقت بذارم و شناسایی کنم مشکل رو...

تشکر از جوابتون

**Comment by alitnk** [comment]
مشکل باید حل شده باشه - فکی نمیکنم دوباره اتفاق بیفته. ولی اگر دوباره مشاهده کردید لطف کنید و باز کنید ایشو رو دوباره.
ممنون
