### ISSUE TITLE
stats not updating - Error While Checking Profile

### ISSUE THREAD

**Issue by BlackSnowDot** [matnbaz/matnbaz#282]
همون مشکل [issues 280](https://github.com/matnbaz/matnbaz/issues/280)
و هیچ چیزی آپدیت نمیشه

**Comment by alitnk** [comment]
لینک صفحه ای که چک کردید و خطا داد رو هم ممکنه بفرستید؟

**Comment by BlackSnowDot** [comment]
همینطور در این [صفحه](https://matnbaz.net/github/users) چند روزه که هیچی آپدیت نشده [برای مثال کامیت ها]

**Comment by alitnk** [comment]
> برای [مثال این صفحه](https://matnbaz.net/github/BlackSnowDot)
این صفحه باز میشه. نمی‌دونم چه مشکلی داره برای شما.

درمورد آپدیت شدن صفحه کاربران هم تا جایی که من دیدم بروز هست. تعداد کامیت های پرایوت هم شمرده نمیشه - فقط پابلیک ها.
