### ISSUE TITLE
Is website down?

### ISSUE THREAD

**Issue by AmirAli-AZ** [matnbaz/matnbaz#283]
![Screenshot_20221120_142149](https://user-images.githubusercontent.com/84965706/202898248-f648f7d4-77d2-447a-95ca-af702dd83ac9.jpg)

**Comment by alitnk** [comment]
ArvanCloud is having some issues. I'm guessing that's the reason. I can't even access the dashboard.

Will probably move the hosting to Liara when I get the chance.

**Comment by alitnk** [comment]
Working now. Thanks for opening the issue.
