### ISSUE TITLE
Issue from load updated readme file from repo

### ISSUE THREAD

**Issue by TREER00T** [matnbaz/matnbaz#287]
سلام و خسته نباشید یک مشکل در بحث نمایش ویرایشات انجام شده در فایل readme.md ریپازیتوری برای من به وجود آمده مشکل از اینجا شروع میشه که من ویرایشاتی روی فایل readme پروژه ام انجام داده ام حدودا دو سه روز پیش بود اما ظاهرا اپدیت در این [لینک](https://matnbaz.net/explore?searchTerm=opensql) لحاظ نشده میخواستم بدونم ایا دلیلی داشته که اینکار انجام بشه یا این یک باگ هس ؟

[لینک پروژه من](github.com/treegex/opensql)

**Comment by alitnk** [comment]
سلام ممنون
آپدیت مخزن ها هر شب اتفاق میفته. من الان دستی تریگر کردم آپدیت رو و باید تا یک ساعت دیگه حدودا آپدیت بشن همه شون. اگر آپدیت نشد ممکنه یه مشکلی داشته باشه.
