### ISSUE TITLE
latest change date on each repository page

### ISSUE THREAD

**Issue by agn-7** [matnbaz/matnbaz#44]
It seems the latest change date value on each repository page is not correct as when I updated a repository for example last hour I'll see the same lastest change date value in my other repositories as well.

**Comment by alitnk** [comment]
Hey, thanks for opening the issue.

We update repositories every 24 hours, so the changes on repositories (README changes, stargazers count, latest change date, etc.) won't be reflected at the moment you cause them, but instead will be reflected [when the extraction process runs](https://github.com/matnbaz/matnbaz/blob/main/apps/server/src/github-extractor/github-extractor.scheduler.ts#L12).
