### ISSUE TITLE
fIxed thead of table in contributors section 

### ISSUE THREAD

**Issue by pooooriya** [matnbaz/matnbaz#52]
it's good to add a fixed position when the user scrolls in the bottom of the table

**Comment by pooooriya** [comment]
we need to change the table because we need a sticky thead, we have to put our scroll in the table not in page and overflow of page most be hidden, if we create two thread and control them with javascript, in responsive cant handle table x scroll!
so we have a responsive table with scrolling inside the table not on page!

**Comment by alitnk** [comment]
https://github.com/matnbaz/matnbaz/commit/391e98b5fabcdfe4b33565b2ebf94c072a96b8f3 done.
