### ISSUE TITLE
table in contributers need to change into virtual list not a regular table 

### ISSUE THREAD

**Issue by pooooriya** [matnbaz/matnbaz#56]
we need to change the table in top users to a virtualized list because when you scroll down to the end of the list, the dom gets heavy and slow.

**Comment by pooooriya** [comment]
https://react-table.tanstack.com/docs/overview
it can help us to implement this section

**Comment by alitnk** [comment]
https://github.com/matnbaz/matnbaz/commit/3cdd7cc675c6a36b3ae3b24c129a005a28382989 this fixes the issue.
