### ISSUE TITLE
Running project

### ISSUE THREAD

**Issue by rdwnsjjd** [matnbaz/matnbaz#58]
How to run project?
I want to run it locally.
how to do it?

**Comment by alitnk** [comment]
I will add documentation on this as soon as i can.

**Comment by rdwnsjjd** [comment]
That's OK.
but if possible, tell me what to do for now!

**Comment by ehsanghaffarii** [comment]
Is it possible to launch with Docker? I wanna fix the #95 issue

**Comment by alitnk** [comment]
I don't really use Docker for development of Matnbaz and the Docker files are old, I doubt if they are compatible with the current state of the project.
I'll try to add documentation on how to run the project locally soon, now that most of the features are implemented.

**Comment by alitnk** [comment]
https://github.com/matnbaz/matnbaz/wiki/Running-locally
